//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SendGridDotNetCore.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EmailComponents {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmailComponents() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SendGridDotNetCore.Common.EmailComponents", typeof(EmailComponents).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send grid API key.
        /// </summary>
        public static string apiKey {
            get {
                return ResourceManager.GetString("apiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email To.
        /// </summary>
        public static string emailTo {
            get {
                return ResourceManager.GetString("emailTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email To user name.
        /// </summary>
        public static string emailToUserName {
            get {
                return ResourceManager.GetString("emailToUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from email.
        /// </summary>
        public static string fromEmail {
            get {
                return ResourceManager.GetString("fromEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from email user name.
        /// </summary>
        public static string fromEmaliUserName {
            get {
                return ResourceManager.GetString("fromEmaliUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Hello World&lt;/strong&gt; &lt;br /&gt; 
        ///&lt;body bgcolor=&quot;#ffffff&quot; text=&quot;#000000&quot;&gt;
        ///        This is the body text&lt;br&gt;
        ///&lt;div class=&quot;moz-signature&quot;&gt;&lt;i&gt;&lt;br&gt;
        ///&lt;br&gt;
        ///Regards&lt;br&gt;
        ///Mr. Dev Chowdory&lt;br&gt;
        ///&lt;/i&gt;&lt;/div&gt;
        ///&lt;/body&gt;.
        /// </summary>
        public static string htmlContent {
            get {
                return ResourceManager.GetString("htmlContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello world from sendgrid email.
        /// </summary>
        public static string plainTextContent {
            get {
                return ResourceManager.GetString("plainTextContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending email using Sendgrid.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
    }
}
